config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :quotes do
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]
    end
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
    # after_create_commit -> { broadcast_prepend_later_to "quotes" }
    # after_update_commit -> { broadcast_replace_later_to "quotes" } 
    # after_destroy_commit -> { broadcast_remove_to "quotes" }
    belongs_to :company
    has_many :line_item_dates, dependent: :destroy
    has_many :line_items, through: :line_item_dates

    broadcasts_to ->(quote) { [ quote.company, "quotes" ] }, inserts_by: :prepend # this is equal to above three line

    validates :name, presence: true
    scope :ordered, -> { order(id: :desc) }

    def total_price
      line_items.sum(&:total_price)
    end

  end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :set_quote, only: [:show, :edit, :update, :destroy]
  
    def index
      @quotes = current_company.quotes.ordered
    end
  
    def show
      @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
    end
  
    def new
      @quote = Quote.new
    end
  
    def create
      @quote = current_company.quotes.build(quote_params)
  
      if @quote.save
        respond_to do |format|
          format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
          format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
    end
  
    def update
      if @quote.update(quote_params)
        respond_to do |format|
          format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
          format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
        end
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @quote.destroy
    
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
      end
    end
  
    private
  
    def set_quote
      @quote = current_company.quotes.find(params[:id])
    end
  
    def quote_params
      params.require(:quote).permit(:name)
    end
  end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    You don't have any quotes yet!
  </p>

  <%= link_to "Add quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: "new_quote"} %>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
  <%= form_error_notification(quote)%>

  <%= f.input :name, input_html: { autofocus: true } %>
   <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
<div class="quote">
  <%= link_to quote.name, quote_path(quote), data: {turbo_frame: "_top"} %>
  <div class="quote__actions">
    <%= button_to "Delete",
                  quote_path(quote),
                  method: :delete,
                  class: "btn btn--light" %>
    <%= link_to "Edit",
                edit_quote_path(quote),
                class: "btn btn--light" %>
  </div>
</div>
<% end %>

app/views/quotes/_total.html.erb
<footer class="quote-total">
  <div class="quote-total__inner container">
    <div>Total:</div>
    <div><%= number_to_currency quote.total_price %></div>
  </div>
</footer>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>
<%= turbo_frame_tag @quote  do %>
  <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_company, 'quotes' %>

<main class="container">
    <div class="header">
        <h1>Quotes</h1>
        <%= link_to "New quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: 'new_quote' } %>
    </div>
    <%= turbo_frame_tag Quote.new %>

  <%= turbo_frame_tag "quotes" do %>
    <%= render "quotes/empty_state" %>
    <%= render @quotes %>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container mb-xxxxl">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>

    <%= link_to "New date",
                new_quote_line_item_date_path(@quote),
                data: { turbo_frame: "new_line_item_date" },
                class: "btn btn--primary" %>
  </div>

  <%= turbo_frame_tag LineItemDate.new %>
<%= turbo_frame_tag "line_item_dates" do  %>
  <%= render @line_item_dates, quote: @quote %>
  <% end %>
</main>

<%= turbo_frame_tag dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>